[package]
name = "acpi-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
# acpi_tables crate doesn't exist on crates.io
# We'll use direct byte manipulation for ACPI tables
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
